services:
  db:
    image: postgres:15-alpine
    container_name: sansocrates_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=filosofia_db
      - POSTGRES_USER=filosofia_user
      - POSTGRES_PASSWORD=filosofia_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U filosofia_user -d filosofia_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sansocrates_network

  web:
    build: .
    container_name: sansocrates_blog
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers 3 config.wsgi:application"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - sansocrates_network

networks:
  sansocrates_network:
    name: sansocrates_network

volumes:
  postgres_data:
