services:
  web:
    build: .
    container_name: sansocrates_blog
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

networks:
  default:
    name: sansocrates_network
